bind 0.0.0.0                         # 监听所有网卡，允许其他容器连接 Sentinel
port 26379                           # Sentinel 监听端口

sentinel monitor redis-master redis-master 6379 2
# 监控名为 redis-master 的主节点
# redis-master：主节点地址
# 6379：主节点端口
# 2：至少 2 个 Sentinel 同意主节点下线，才认为主节点客观下线

sentinel down-after-milliseconds redis-master 1000
# 1 秒内无法与主节点正常通信，则认为主节点主观下线
